# Generated by Django 5.2 on 2025-04-07 23:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacker', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('title', models.CharField(max_length=50, verbose_name='Превью отзыва')),
                ('feedback', models.TextField(max_length=500, verbose_name='Отзыв')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='tours',
            name='description',
            field=models.TextField(max_length=500, verbose_name='О туре'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
